Magento collection
crowdsecurity/hub pull request #378
Opened 2022-02-11 14:35 UTC by AlteredCoder

2022-02-11 16:30 UTC, he2ss approved these changes

2022-02-11 16:30 UTC, he2ss commented on parsers/s01-parse/crowdsecurity/magento-extension-logs.md
> +Parser for the CrowdSec Magento Extension.
missing link for the extension

2022-02-15 10:48 UTC, buixor requested changes
minor remarks + do we want to add CC stuffing scenario or similar before merging ?

2022-02-15 10:48 UTC, buixor commented on collections/crowdsecurity/magento.md
> +## OPNSense collection
Leftover OPNSense

2022-04-01 16:10 UTC, buixor requested changes
minor changes

2022-04-01 16:10 UTC, buixor commented on collections/crowdsecurity/magento.yaml
> +  - crowdsecurity/dateparse-enrich
geoip enrich

2022-04-29 09:31 UTC, buixor approved these changes
lgtm

2022-10-21 14:22 UTC, merged