Add nginx_req_limit_exceeded scenario
crowdsecurity/hub pull request #427
Opened 2022-04-01 15:30 UTC by sbs2001

Fixes https://github.com/crowdsecurity/hub/issues/420

2022-04-04 08:13 UTC, buixor requested changes
imp doc, but overall good :)

2022-04-04 08:13 UTC, buixor commented on scenarios/crowdsecurity/nginx_req_limit_exceeded.md
> +Detects IPs which violate nginx's user set request limit.
Please add info about bucket :)

2022-04-11 07:31 UTC, sbs2001 commented on scenarios/crowdsecurity/nginx_req_limit_exceeded.md
> +Detects IPs which violate nginx's user set request limit.
done

2022-04-22 07:55 UTC, buixor approved these changes
lgtm

2022-04-22 07:55 UTC, merged