Added AWS ALB access log parser
crowdsecurity/hub pull request #716
Opened 2023-04-27 21:42 UTC by Zaulao

2023-04-28 12:23 UTC, Zaulao commented
No problem! Just added it

2023-04-28 12:46 UTC, Zaulao commented
Sorry for the typo, I got it wrong after forking the project to prepare de PR

2023-06-14 14:30 UTC, LaurenceJJones requested changes
Small changes but we also need tests for some scenarios. If you can bring up to upstream changes and also do my requested changes I can create the scenarios tests.

2023-06-14 14:30 UTC, LaurenceJJones commented on .tests/aws-alb-logs/config.yaml
> +parsers:
can we add s00 stage parser

`- crowdsecurity/syslog-logs`

Even though it is not really used it "real runtim" there is always a stage s00 parser

2023-06-14 14:30 UTC, LaurenceJJones commented on .tests/aws-alb-logs/parser.assert
> +len(results) == 3
Once you add stage s00 parser you will need to regen .assert

2023-06-28 14:09 UTC, Zaulao commented
Is there anything else I can do here?

2023-06-28 14:51 UTC, blotus approved these changes

2023-06-28 14:52 UTC, blotus commented
Hello,

Sorry about the delay; the PR fell through the cracks.

I'm merging it; thanks for the contribution!

2023-06-28 14:52 UTC, merged