feat: Add keycloak parser, scenario and collection
crowdsecurity/hub pull request #758
Opened 2023-06-11 19:12 UTC by lperdereau

This PR consists of implementing:

- [x]  A keycloak logs parser `parsers/s01-parse/inherent-io/keycloak-logs`
- [x]  A keycloak scenario for quick bruteforce attack `scenarios/inherent-io/keycloak-bf`
- [x]  A keycloak scenario for slow bruteforce attack `scenarios/inherent-io/keycloak-slow-bf`
- [x]  A keycloak collection `collection/inherent-io/keycloak`

2023-06-12 08:42 UTC, blotus commented on parsers/s01-parse/inherent-io/keycloak-logs.yaml
> +filter: 1 == 1
Please filter on the actual program name

2023-06-12 08:42 UTC, blotus commented on parsers/s01-parse/inherent-io/keycloak-logs.yaml
> +debug: true
Remove or comment this

2023-06-12 08:44 UTC, blotus commented on scenarios/inherent-io/keycloak-bf.yaml
> +name: inherent-io/keycloak-bf
Should probably be `inherent-io/keycloak-user-enum` ?

2023-06-12 08:44 UTC, blotus commented on scenarios/inherent-io/keycloak-slow-bf.yaml
> +name: inherent-io/keycloak-slow-bf
Same as above

2023-06-12 08:58 UTC, LaurenceJJones requested changes
Reviewed, please see requested changes

2023-06-12 08:58 UTC, LaurenceJJones commented on collections/inherent-io/keycloak.md
> +Keycloak support : parser and brute-force detection
Provide a configuration example? Does it log to a file if so where is the file location?

```
filenames:
  - /path/to/log
labels:
  type: keycloak
  ```
  Is it a docker program
 ```
 source: docker
 container_name:
   - keycloak
 labels:
   type: keycloak
   ```

2023-06-12 15:50 UTC, lperdereau commented on parsers/s01-parse/inherent-io/keycloak-logs.yaml
> +filter: 1 == 1
@blotus and you're asking me to change my filter to one based on the program name.
But I haven't understood how crowdsec can find out the name of the program from a file or a stdout container.

2023-06-12 16:03 UTC, lperdereau commented on parsers/s01-parse/inherent-io/keycloak-logs.yaml
> +filter: 1 == 1
This thing configure the evt.Parsed.program ?

```
labels:
  type: keycloak
```

2023-06-12 16:42 UTC, lperdereau commented
@blotus, @LaurenceJJones  Thank you for your review, I've learnt a lot.

2023-06-13 08:49 UTC, LaurenceJJones approved these changes
LGTM, bitwarden test is flakey

2023-06-13 14:20 UTC, blotus approved these changes

2023-06-13 14:20 UTC, merged