Paperless ngx
crowdsecurity/hub pull request #771
Opened 2023-07-01 09:21 UTC by andreasbrett

Add [Paperless-ngx](https://github.com/paperless-ngx/paperless-ngx) collection incl. parser and scenarios to the hub

2023-07-02 20:46 UTC, LaurenceJJones commented on .tests/paperless-ngx-logs/parser.assert
Could you include all of the parser assert output not just for s01-parse stage

2023-07-02 20:47 UTC, LaurenceJJones requested changes
Other than single comment once that is done, can be merged

Also thank you for spending the time making this! 🎆

2023-07-02 21:02 UTC, andreasbrett commented on .tests/paperless-ngx-logs/parser.assert
fair point. latest commit includes all the parser assert output.

2023-07-03 10:00 UTC, LaurenceJJones approved these changes
LGTM flakey tests (outside scope of this PR)

2023-07-03 10:00 UTC, merged