Add Authentik collection to hub
crowdsecurity/hub pull request #858
Opened 2023-10-17 19:51 UTC by afirix

Adding a collection, a parser, and a scenario for Authentik (https://goauthentik.io/).

2023-10-19 14:54 UTC, LaurenceJJones commented on parsers/s01-parse/firix/authentik-logs.yaml
> +  - filter: "JsonExtract(evt.Line.Raw, 'action') == 'login_failed'"
Could we use `evt.Parsed.message` instead of raw? sometimes, user want to log to another engine like syslog file this would cause an issue.

2023-10-19 14:56 UTC, LaurenceJJones requested changes
Request, one change to rename all `evt.Line.Raw` to `evt.Parsed.message` incase people use a logging service that doesnt pre treat the line. Once that is done, then all ready for merge

2023-10-19 18:01 UTC, afirix commented
Done as requested. Tests still pass and all the functionality seem to be working as before the change.

2023-10-20 06:47 UTC, LaurenceJJones commented
> Done as requested. Tests still pass and all the functionality seem to be working as before the change.

Yeah, it won't change anything on the surface, but if they use any logging facility

Waiting for automatic tests, then I will merge

2023-10-20 08:05 UTC, LaurenceJJones approved these changes
LGTM, thank you for your contribution to the CrowdSec community

2023-10-20 08:05 UTC, merged