Adding WAF Coraza+Caddy parser
crowdsecurity/hub pull request #942
Opened 2024-01-29 21:03 UTC by Barnoux

Hello,

Hope this parser will find some love. 
The goal of this parser is to parse waf alert from coraza when coraza is integreted as a plugin in caddy.

It is hugely inspired on the work down by [the modsecurity.yaml](https://github.com/crowdsecurity/hub/blob/master/parsers/s01-
parse/crowdsecurity/modsecurity.yaml)

It's time for me to eat a cake and take a nap.

2024-01-29 21:32 UTC, LaurenceJJones commented on scenarios/barnoux/coraza.yaml
> +filter: evt.Meta.log_type == 'modsecurity' && evt.Parsed.ruleid == '949110'
rather being coraza maybe should be named something to do with CRS?

2024-01-29 21:35 UTC, LaurenceJJones commented
Hey 👋🏻 Thank you for opening a PR!

We going to be need some tests for the parsers and scenarios. I left an initial comment since coraza is a modsecurity implementation meaning a scenario on the rule id might not be best since you dont have to use CRS.

2024-01-31 20:55 UTC, Barnoux commented on scenarios/barnoux/coraza.yaml
> +filter: evt.Meta.log_type == 'modsecurity' && evt.Parsed.ruleid == '949110'
yes you right, i will try to find a better name.

2024-01-31 21:04 UTC, Barnoux commented
> Hey 👋🏻 Thank you for opening a PR!
> 
> We going to be need some tests for the parsers and scenarios. I left an initial comment since coraza is a modsecurity implementation meaning a scenario on the rule id might not be best since you dont have to use CRS.

What type of input do you need for testing ? The rule id chosed in the scenario is based on the inbound anomaly score that is triggered and can be tuned by the user (https://coreruleset.org/docs/concepts/anomaly_scoring/#anomaly-score-thresholds). I did't find a better way to handle this.

2024-02-05 07:59 UTC, LaurenceJJones requested changes

2024-02-05 07:59 UTC, LaurenceJJones commented on scenarios/barnoux/crs-anomaly-score.yaml
> +blackhole: 2m
If you have a blackhole key it be best to also have a groupby since a single trigger will blackhole the whole bucket

2024-02-17 19:09 UTC, Barnoux commented on scenarios/barnoux/crs-anomaly-score.yaml
> +blackhole: 2m
is it ok now ?

2024-02-20 11:14 UTC, LaurenceJJones commented
Okay, the last thing is adding a `collection` of

Parser
Scenarios (could include our standard modsec one 🤷🏻 )

2024-02-29 22:35 UTC, Barnoux commented
> Okay, the last thing is adding a `collection` of
> 
> Parser Scenarios (could include our standard modsec one 🤷🏻 )

I add the collection, is it looking good ?

2024-08-19 08:35 UTC, ubergeek77 commented
Hey there, just passing by. I came across this PR as it's exactly what I'm looking for.

@LaurenceJJones , hope you don't mind the ping after so long, but are any more changes needed to get this merged? :slightly_smiling_face:

2024-11-04 07:23 UTC, Barnoux commented
> The only issue I have with is the scenario as its close to the original one we have for modsecurity. However, I did forget about this, so ill do this now.

What can i do to help you on this one ?

2024-11-04 08:48 UTC, LaurenceJJones commented
I will look into it, the only thing I dont like is the modification that was needed to the original caddy parser.

Maybe we can move this too `s02` level instead cause if at any point they change the log handler name it will break the chain. Moving to `s02` means we can still keep the original filter and then let the natural chain processing happen. The only thing is we have to execute before the original enrichers but this can be looked into.

2025-02-03 21:07 UTC, Barnoux commented
Hello, how can i help to close this MR ?

2025-02-03 21:29 UTC, merged

2025-02-03 21:50 UTC, LaurenceJJones commented
> Hello, how can i help to close this MR ?

Apologies it was on me, I decided just to merge as is, saves the back and forth plus me forgetting to stay on top of this.

If anybody has any issues, please open an issue and link logs but thank you @Barnoux , congratz on a valuable addition to the hub.